import { css } from '@emotion/react';
import Head from 'next/head';
// import Image from 'next/image';
import Link from 'next/link';
import { useEffect, useState } from 'react';
import Layout from '../components/Layout';

const main = css`
  text-align: center;
  margin-top: -1.9rem;
  width: 100vw;
  height: 80vh;
  background-image: url('../images/portada1.jpg');
  background-size: cover;
  position: relative;
`;

const title = css`
  font-family: 'New Tegomin';
  padding-top: 2rem;
  color: black;
  font-weight: 700;
  font-size: 4.8rem;
  text-align: center;
  margin-bottom: 0;
`;

export default function Home(props) {
  useEffect(() => {
    props.refreshUsername();
    console.log(1213);
  }, []);

  return (
    <div>
      <Head>
        <title>TopTip Map</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/images/sunshine.svg" />
      </Head>

      <Layout username={props.username}>
        <main css={main}>
          <image
            src="https://www.adslzone.net/app/uploads-adslzone.net/2019/04/borrar-fondo-imagen.jpg"
            alt="someth"
          />
          <p css={title}>TopTip Map</p>
          {/* <Image css={portadaStyle} src={portada} alt="portada" /> */}
        </main>
      </Layout>
    </div>
  );
}

// export async function getServerSideProps(context) {
//   const { getValidSessionByToken } = await import('../util/database');

//   const sessionToken = context.req.cookies.sessionToken;

//   const session = await getValidSessionByToken(sessionToken);

//   console.log(session);

//   if (!session) {
//     // Redirect the user when they have a session
//     // token by returning an object with the `redirect` prop
//     // https://nextjs.org/docs/basic-features/data-fetching#getserversideprops-server-side-rendering
//     return {
//       redirect: {
//         destination: '/login?returnTo=/map',
//         permanent: false,
//       },
//     };
//   }

//   return {
//     props: {},
//   };
// }
