import { css, Global } from '@emotion/react';
import Head from 'next/head';
// import Image from 'next/image';
// import Link from 'next/link';
import Layout from '../components/Layout';

// import portada from '../public/images/portada.jpg';

// import { myGlobalStyles } from '../styles/myGlobalStyles';

const main = css`
  margin-top: 0;
  /* padding-top: 5rem; */
  width: 100vw;
  height: 92vh;
  background-image: url('../images/portada1.jpg');
  background-size: cover;
  position: relative;
`;

const title = css`
  font-family: 'New Tegomin';
  margin-top: 1rem;
  color: black;
  font-weight: 700;
  font-size: 4.6rem;
  text-align: center;
  margin-bottom:0;
`;

// const portadaStyle = css`
//   min-height: 70vh;
//   height: 5rem;
//   width: 10rem;
// `;

export default function Home() {
  return (
    <div>
      <Head>
        <title>TopTip Map</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.svg" />
      </Head>

      <Layout>
        <main css={main}>
          <p css={title}>TopTip Map</p>
          {/* <Image css={portadaStyle} src={portada} alt="portada" /> */}
        </main>

      </Layout>
    </div>
  );
}